import { PrismaClient, PlayerRole, BattingStyle, BowlingStyle, BattingPosition, PlayerForm, PitchType, BoundarySize, OutfieldSpeed } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🏏 Seeding cricket team database...')

  // Create a season
  const season = await prisma.season.create({
    data: {
      name: 'Winter League 2026',
      startDate: new Date('2026-01-15'),
      endDate: new Date('2026-04-30'),
      isActive: true,
      description: 'Annual winter cricket league',
      totalMatches: 12,
      matchesPlayed: 6,
      wins: 4,
      losses: 1,
      draws: 1,
      currentPosition: 3,
      totalTeams: 8,
    },
  })

  // Create players with diverse roles and skills
  const players = await Promise.all([
    prisma.player.create({
      data: {
        name: 'Raj Kumar',
        email: 'raj.kumar@email.com',
        phone: '+1-555-0101',
        jerseyNumber: 7,
        primaryRole: PlayerRole.BATSMAN,
        battingStyle: BattingStyle.RIGHT_HAND,
        bowlingStyle: BowlingStyle.MEDIUM,
        battingPosition: BattingPosition.TOP_ORDER,
        battingSkill: 9,
        bowlingSkill: 4,
        fieldingSkill: 8,
        experienceLevel: 9,
        captainChoice: 1,
        isCaptain: true,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 6,
            matchesPlayed: 6,
            innings: 6,
            runsScored: 285,
            ballsFaced: 210,
            fours: 32,
            sixes: 12,
            notOuts: 2,
            highestScore: 78,
            fifties: 3,
            currentForm: PlayerForm.EXCELLENT,
            catches: 4,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Amit Singh',
        email: 'amit.singh@email.com',
        jerseyNumber: 11,
        primaryRole: PlayerRole.ALL_ROUNDER,
        battingStyle: BattingStyle.LEFT_HAND,
        bowlingStyle: BowlingStyle.SPIN_OFF,
        battingPosition: BattingPosition.MIDDLE_ORDER,
        battingSkill: 7,
        bowlingSkill: 8,
        fieldingSkill: 7,
        experienceLevel: 8,
        captainChoice: 1,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 6,
            matchesPlayed: 5,
            innings: 4,
            runsScored: 145,
            ballsFaced: 98,
            fours: 14,
            sixes: 6,
            highestScore: 52,
            fifties: 1,
            oversBowled: 24,
            runsConceded: 156,
            wicketsTaken: 8,
            maidens: 2,
            bestBowling: '3/22',
            currentForm: PlayerForm.GOOD,
            catches: 3,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Vikram Patel',
        email: 'vikram.patel@email.com',
        jerseyNumber: 45,
        primaryRole: PlayerRole.BOWLER,
        battingStyle: BattingStyle.RIGHT_HAND,
        bowlingStyle: BowlingStyle.FAST,
        battingPosition: BattingPosition.LOWER_ORDER,
        battingSkill: 3,
        bowlingSkill: 9,
        fieldingSkill: 6,
        experienceLevel: 7,
        captainChoice: 1,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 6,
            matchesPlayed: 6,
            oversBowled: 28,
            runsConceded: 168,
            wicketsTaken: 12,
            maidens: 3,
            bestBowling: '4/28',
            fourWickets: 1,
            currentForm: PlayerForm.EXCELLENT,
            catches: 2,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Suresh Menon',
        email: 'suresh.menon@email.com',
        jerseyNumber: 1,
        primaryRole: PlayerRole.WICKETKEEPER,
        battingStyle: BattingStyle.RIGHT_HAND,
        bowlingStyle: BowlingStyle.NONE,
        battingPosition: BattingPosition.MIDDLE_ORDER,
        battingSkill: 7,
        bowlingSkill: 1,
        fieldingSkill: 9,
        experienceLevel: 8,
        captainChoice: 1,
        isWicketkeeper: true,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 6,
            matchesPlayed: 6,
            innings: 5,
            runsScored: 168,
            ballsFaced: 130,
            fours: 18,
            sixes: 5,
            notOuts: 1,
            highestScore: 45,
            currentForm: PlayerForm.GOOD,
            catches: 8,
            stumpings: 3,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Karthik Nair',
        email: 'karthik.nair@email.com',
        jerseyNumber: 23,
        primaryRole: PlayerRole.BATSMAN,
        battingStyle: BattingStyle.RIGHT_HAND,
        bowlingStyle: BowlingStyle.MEDIUM,
        battingPosition: BattingPosition.OPENER,
        battingSkill: 8,
        bowlingSkill: 3,
        fieldingSkill: 7,
        experienceLevel: 6,
        captainChoice: 2,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 6,
            matchesPlayed: 2,
            innings: 2,
            runsScored: 35,
            ballsFaced: 40,
            fours: 4,
            sixes: 1,
            highestScore: 22,
            currentForm: PlayerForm.AVERAGE,
            catches: 1,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Dinesh Kumar',
        email: 'dinesh.kumar@email.com',
        jerseyNumber: 99,
        primaryRole: PlayerRole.ALL_ROUNDER,
        battingStyle: BattingStyle.RIGHT_HAND,
        bowlingStyle: BowlingStyle.MEDIUM_FAST,
        battingPosition: BattingPosition.FINISHER,
        battingSkill: 6,
        bowlingSkill: 7,
        fieldingSkill: 8,
        experienceLevel: 5,
        captainChoice: 1,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 5,
            matchesPlayed: 4,
            innings: 3,
            runsScored: 78,
            ballsFaced: 45,
            fours: 6,
            sixes: 4,
            notOuts: 1,
            highestScore: 35,
            oversBowled: 16,
            runsConceded: 98,
            wicketsTaken: 5,
            bestBowling: '2/18',
            currentForm: PlayerForm.GOOD,
            catches: 2,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Pradeep Iyer',
        email: 'pradeep.iyer@email.com',
        jerseyNumber: 18,
        primaryRole: PlayerRole.BATSMAN,
        battingStyle: BattingStyle.LEFT_HAND,
        bowlingStyle: BowlingStyle.SPIN_LEG,
        battingPosition: BattingPosition.OPENER,
        battingSkill: 8,
        bowlingSkill: 4,
        fieldingSkill: 6,
        experienceLevel: 7,
        captainChoice: 1,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 6,
            matchesPlayed: 5,
            innings: 5,
            runsScored: 198,
            ballsFaced: 165,
            fours: 22,
            sixes: 8,
            notOuts: 1,
            highestScore: 62,
            fifties: 2,
            currentForm: PlayerForm.EXCELLENT,
            catches: 2,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Rahul Menon',
        email: 'rahul.menon@email.com',
        jerseyNumber: 33,
        primaryRole: PlayerRole.BOWLER,
        battingStyle: BattingStyle.RIGHT_HAND,
        bowlingStyle: BowlingStyle.SPIN_OFF,
        battingPosition: BattingPosition.LOWER_ORDER,
        battingSkill: 4,
        bowlingSkill: 8,
        fieldingSkill: 7,
        experienceLevel: 6,
        captainChoice: 2,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 6,
            matchesPlayed: 4,
            oversBowled: 20,
            runsConceded: 125,
            wicketsTaken: 6,
            maidens: 2,
            bestBowling: '2/24',
            currentForm: PlayerForm.GOOD,
            catches: 3,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Anand Pillai',
        email: 'anand.pillai@email.com',
        jerseyNumber: 77,
        primaryRole: PlayerRole.BOWLER,
        battingStyle: BattingStyle.LEFT_HAND,
        bowlingStyle: BowlingStyle.SPIN_LEFT_ARM,
        battingPosition: BattingPosition.LOWER_ORDER,
        battingSkill: 3,
        bowlingSkill: 8,
        fieldingSkill: 6,
        experienceLevel: 5,
        captainChoice: 2,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 5,
            matchesPlayed: 3,
            oversBowled: 14,
            runsConceded: 88,
            wicketsTaken: 5,
            maidens: 1,
            bestBowling: '2/20',
            currentForm: PlayerForm.AVERAGE,
            catches: 1,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Mohit Verma',
        email: 'mohit.verma@email.com',
        jerseyNumber: 55,
        primaryRole: PlayerRole.BOWLER,
        battingStyle: BattingStyle.RIGHT_HAND,
        bowlingStyle: BowlingStyle.FAST,
        battingPosition: BattingPosition.LOWER_ORDER,
        battingSkill: 3,
        bowlingSkill: 7,
        fieldingSkill: 5,
        experienceLevel: 4,
        captainChoice: 2,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 6,
            matchesPlayed: 3,
            oversBowled: 12,
            runsConceded: 82,
            wicketsTaken: 4,
            bestBowling: '2/26',
            currentForm: PlayerForm.AVERAGE,
            catches: 0,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Sanjay Rao',
        email: 'sanjay.rao@email.com',
        jerseyNumber: 21,
        primaryRole: PlayerRole.BOWLER,
        battingStyle: BattingStyle.RIGHT_HAND,
        bowlingStyle: BowlingStyle.MEDIUM_FAST,
        battingPosition: BattingPosition.LOWER_ORDER,
        battingSkill: 4,
        bowlingSkill: 7,
        fieldingSkill: 6,
        experienceLevel: 6,
        captainChoice: 1,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 6,
            matchesPlayed: 5,
            innings: 2,
            runsScored: 28,
            ballsFaced: 18,
            fours: 3,
            sixes: 1,
            oversBowled: 22,
            runsConceded: 145,
            wicketsTaken: 7,
            maidens: 2,
            bestBowling: '3/24',
            currentForm: PlayerForm.GOOD,
            catches: 2,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Arjun Das',
        email: 'arjun.das@email.com',
        jerseyNumber: 8,
        primaryRole: PlayerRole.BOWLER,
        battingStyle: BattingStyle.LEFT_HAND,
        bowlingStyle: BowlingStyle.FAST,
        battingPosition: BattingPosition.LOWER_ORDER,
        battingSkill: 2,
        bowlingSkill: 8,
        fieldingSkill: 7,
        experienceLevel: 4,
        captainChoice: 2,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 4,
            matchesPlayed: 4,
            oversBowled: 18,
            runsConceded: 108,
            wicketsTaken: 8,
            maidens: 2,
            bestBowling: '3/18',
            currentForm: PlayerForm.EXCELLENT,
            catches: 1,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Ravi Sharma',
        email: 'ravi.sharma@email.com',
        jerseyNumber: 47,
        primaryRole: PlayerRole.BATSMAN,
        battingStyle: BattingStyle.RIGHT_HAND,
        bowlingStyle: BowlingStyle.NONE,
        battingPosition: BattingPosition.FINISHER,
        battingSkill: 7,
        bowlingSkill: 1,
        fieldingSkill: 8,
        experienceLevel: 5,
        captainChoice: 1,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 6,
            matchesPlayed: 5,
            innings: 5,
            runsScored: 125,
            ballsFaced: 68,
            fours: 10,
            sixes: 9,
            notOuts: 2,
            highestScore: 42,
            currentForm: PlayerForm.GOOD,
            catches: 4,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Vikash Reddy',
        email: 'vikash.reddy@email.com',
        jerseyNumber: 36,
        primaryRole: PlayerRole.BATSMAN,
        battingStyle: BattingStyle.RIGHT_HAND,
        bowlingStyle: BowlingStyle.SPIN_OFF,
        battingPosition: BattingPosition.MIDDLE_ORDER,
        battingSkill: 7,
        bowlingSkill: 3,
        fieldingSkill: 6,
        experienceLevel: 6,
        captainChoice: 2,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 5,
            matchesPlayed: 3,
            innings: 3,
            runsScored: 85,
            ballsFaced: 72,
            fours: 9,
            sixes: 2,
            highestScore: 38,
            currentForm: PlayerForm.AVERAGE,
            catches: 2,
          },
        },
      },
    }),
    prisma.player.create({
      data: {
        name: 'Amit Shah',
        email: 'amit.shah@email.com',
        jerseyNumber: 14,
        primaryRole: PlayerRole.BATSMAN,
        battingStyle: BattingStyle.LEFT_HAND,
        bowlingStyle: BowlingStyle.NONE,
        battingPosition: BattingPosition.OPENER,
        battingSkill: 8,
        bowlingSkill: 1,
        fieldingSkill: 7,
        experienceLevel: 7,
        captainChoice: 1,
        seasonStats: {
          create: {
            seasonId: season.id,
            matchesAvailable: 6,
            matchesPlayed: 4,
            innings: 4,
            runsScored: 165,
            ballsFaced: 145,
            fours: 20,
            sixes: 4,
            notOuts: 1,
            highestScore: 58,
            fifties: 1,
            currentForm: PlayerForm.GOOD,
            catches: 3,
          },
        },
      },
    }),
  ])

  console.log(`✅ Created ${players.length} players`)

  // Create opponents
  const opponents = await Promise.all([
    prisma.opponent.create({
      data: {
        name: 'Thunder Hawks',
        shortName: 'THK',
        overallStrength: 8,
        battingStrength: 7,
        bowlingStrength: 9,
        fieldingStrength: 7,
        keyPlayers: ['Marcus Johnson (Fast bowler)', 'David Chen (Batsman)'],
        notes: 'Strong fast bowling attack, can be vulnerable against spin',
        playingStyle: 'Aggressive, pace-heavy bowling',
        matchesPlayed: 2,
        matchesWon: 1,
        matchesLost: 1,
      },
    }),
    prisma.opponent.create({
      data: {
        name: 'Royal Strikers',
        shortName: 'RST',
        overallStrength: 7,
        battingStrength: 8,
        bowlingStrength: 6,
        fieldingStrength: 7,
        keyPlayers: ['James Wilson (All-rounder)', 'Mike Brown (Batsman)'],
        notes: 'Strong top order, bowling can be expensive',
        playingStyle: 'Batting-focused, like to chase',
        matchesPlayed: 1,
        matchesWon: 1,
        matchesLost: 0,
      },
    }),
    prisma.opponent.create({
      data: {
        name: 'City Lions',
        shortName: 'CTL',
        overallStrength: 6,
        battingStrength: 6,
        bowlingStrength: 6,
        fieldingStrength: 6,
        keyPlayers: ['Tom Harris (Captain)'],
        notes: 'Well-balanced but lacks match winners',
        playingStyle: 'Defensive, tight bowling',
        matchesPlayed: 1,
        matchesWon: 0,
        matchesLost: 1,
      },
    }),
    prisma.opponent.create({
      data: {
        name: 'Storm Riders',
        shortName: 'STR',
        overallStrength: 9,
        battingStrength: 9,
        bowlingStrength: 8,
        fieldingStrength: 9,
        keyPlayers: ['Chris Martin (Star all-rounder)', 'Alex Turner (WK-Batsman)', 'Sam Clarke (Spinner)'],
        notes: 'League leaders, excellent in all departments',
        playingStyle: 'Complete team, adaptable',
        matchesPlayed: 1,
        matchesWon: 0,
        matchesLost: 1,
      },
    }),
  ])

  console.log(`✅ Created ${opponents.length} opponents`)

  // Create venues
  const venues = await Promise.all([
    prisma.venue.create({
      data: {
        name: 'Riverside Ground',
        address: '123 River Road',
        city: 'Springfield',
        pitchType: PitchType.BALANCED,
        boundarySize: BoundarySize.MEDIUM,
        outfieldSpeed: OutfieldSpeed.MEDIUM,
        typicalConditions: 'Usually good for batting in first half, helps spinners later',
        averageFirstInningsScore: 165,
      },
    }),
    prisma.venue.create({
      data: {
        name: 'Central Park Cricket Ground',
        address: '456 Central Ave',
        city: 'Springfield',
        pitchType: PitchType.BATTING_FRIENDLY,
        boundarySize: BoundarySize.SMALL,
        outfieldSpeed: OutfieldSpeed.FAST,
        typicalConditions: 'High-scoring venue, small boundaries favor batsmen',
        averageFirstInningsScore: 185,
      },
    }),
    prisma.venue.create({
      data: {
        name: 'Green Valley Oval',
        address: '789 Valley Drive',
        city: 'Greenville',
        pitchType: PitchType.BOWLING_FRIENDLY,
        boundarySize: BoundarySize.LARGE,
        outfieldSpeed: OutfieldSpeed.SLOW,
        typicalConditions: 'Green pitch helps seamers, large ground makes scoring difficult',
        averageFirstInningsScore: 145,
      },
    }),
    prisma.venue.create({
      data: {
        name: 'Heritage Cricket Club',
        address: '321 Heritage Lane',
        city: 'Oldtown',
        pitchType: PitchType.SPIN_FRIENDLY,
        boundarySize: BoundarySize.MEDIUM,
        outfieldSpeed: OutfieldSpeed.SLOW,
        typicalConditions: 'Dusty pitch, turns significantly from second innings',
        averageFirstInningsScore: 155,
      },
    }),
  ])

  console.log(`✅ Created ${venues.length} venues`)

  // Create upcoming match
  const upcomingMatch = await prisma.match.create({
    data: {
      matchDate: new Date('2026-02-08'),
      matchNumber: 7,
      status: 'UPCOMING',
      importance: 'MUST_WIN',
      seasonId: season.id,
      opponentId: opponents[0].id, // Thunder Hawks
      venueId: venues[0].id, // Riverside Ground
      weather: 'OVERCAST',
      leaguePosition: 3,
      matchesRemaining: 5,
      captainNotes: 'Must win to stay in top 4 contention. Thunder Hawks have a strong pace attack - need solid openers.',
    },
  })

  console.log('✅ Created upcoming match')

  // Create activities
  await prisma.activity.createMany({
    data: [
      {
        type: 'SEASON_STARTED',
        title: 'Winter League 2026 Started',
        description: 'New season kicked off with 8 teams competing',
      },
      {
        type: 'MATCH_UPDATED',
        title: 'Match vs City Lions - Won',
        description: 'Won by 25 runs. Vikram Patel took 4/28.',
        entityType: 'match',
      },
      {
        type: 'PLAYER_UPDATED',
        title: 'Raj Kumar scored 78',
        description: 'Captain led from the front with a match-winning 78.',
        entityType: 'player',
      },
      {
        type: 'SQUAD_SELECTED',
        title: 'Squad selected for Match #7',
        description: 'AI-assisted squad selection for upcoming match vs Thunder Hawks',
        entityType: 'match',
      },
    ],
  })

  console.log('✅ Created activities')
  console.log('🏏 Database seeded successfully!')
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })

